### ISSUE TITLE
listed some issues on demo page

### ISSUE THREAD

**Issue by ShenQingchuan** [Flrande/circu#10]
写在 https://circu.up.railway.app/ 里了

Bug 1: 复制 行内部分文本 会把 一整行 全复制出来

Bug 2: 我刷新了网站之后会在我上次离开的位置留下一个用户光标、过一会会消失😂（Server 问题？）
似乎离开网页时没有自动帮我 disconnect 

Bug 3：浮动 Toolbar 的显示似乎不太灵敏
似乎是拖选的 Selection 才会触发浮动 Toolbar、我用 Shift + 左/右 不会触发

Issue 1：默认字体是霞鹜文楷，但加粗显示似乎不太有好（Test on Mac）

Issue 2: markdown 输入之后、例如**xxx**结束后光标应该在 <b>xxx</b> 之外（右边）后续输入不应该仍然是加粗状态

Issue 3: 按 退格键 Backspace 似乎无法回到上一行

Issue 4: 在某个 “能包含其他 block” 的 block 节点中、当最后一行是一个 block 节点时无法向后插入新的一行，同样的问题对第一行也适用。

Issue 5: 在 代码块 Codeblock 中按 Tab 会改变缩进 text-ident，应该是不符合预期的

（还是复制一遍，如果被冲掉了会有点可惜哈哈哈）

**Comment by Flrande** [comment]
非常感谢你的反馈！我这周是考试周，周五考完试后就会开始处理这些 Bug。

> （还是复制一遍，如果被冲掉了会有点可惜哈哈哈）

建议还是写在这边hhhh，我之前写了个使用文档然后因为一个 schema 错误文档数据就崩掉了。

再次感谢你的测试！😇

**Comment by Flrande** [comment]
Bug 1: 已修复

Bug 2: 我好像复现不出, 是只开了一个标签页吗

Bug 3: 具体是如何不灵敏呢, 工具栏设计上是 mouseup 后才出现

Issue 1: 已更换字体

Issue 2: 这个是 Slate 行内样式的通病, 我之后应该会写个插件来处理

Issue 3: 这个是当时整个文档的数据格式出了问题, 我手动修复了, 应该是拖拽出了 bug, 我还没找到复现方式

Issue 4, 5: 已修复

**Comment by ShenQingchuan** [comment]
> 

对于 Bug3：如果只涉及 mouseup 是不是有点少？因为用户很可能也会使用键盘来制造选取 比如按住 Shift 然后左右键拖选

**Comment by Flrande** [comment]
我个人觉得 mouseup 才代表用户选择行为的结束？🤔好像大部分编辑器都是这样设计的，如果出现选区就显现工具栏，工具栏会阻碍用户正在进行的“选择”行为

**Comment by ShenQingchuan** [comment]
> 我个人觉得 mouseup 才代表用户选择行为的结束？🤔好像大部分编辑器都是这样设计的，如果出现选区就显现工具栏，工具栏会阻碍用户正在进行的“选择”行为

竞品调研了一下：
- Notion/Wolai/飞书云文档   都支持了 键盘制造选区之后 呼出菜单栏
- 很遗憾 AFFiNE 还没有呢 😂  估计 BlockSuite 也有同样的问题，说不定可以把这个问题 也提到 BlockSuite 的 issue 区，不过鉴于你现在就在 BlockSuite 😂直接和你说好像也没差哈哈哈哈

我不觉得你说的阻挡选择这是个问题，选区的变化和浮动 Menu 的位置其实是无关的。

上述三种竞品支持的情况是
- Notion 和 Wolai 都是针对 文档的 Anchor 也就是选取不动的那一边的 绝对位置 进行浮动 Menu 的定位的，所以无论你是向上选择、向下选择，无论怎么拉大拉小选区，浮动菜单的位置都暂时是不变的。（我还特意做好事者看了一下，在 Notion 里，如果滚动页面让选区离开画面，浮动 Menu 是 Fixed 并且过 100ms 左右渐隐消失，而滚动回来又会显示 .... 体验很好，不得不说是这波非常细了。 Wolai 是有这个逻辑，但没有渐隐的动画，也差不多 ）
- 飞书好像有点傻，是每次选取变化后都重新刷新一下位置、看得出会闪一下

**Comment by Flrande** [comment]
诶😨他们不是都是 mouseup 后才出的吗，感觉你说的和我理解的不一样

**Comment by ShenQingchuan** [comment]
> 诶😨他们不是都是 mouseup 后才出的吗，感觉你说的和我理解的不一样

你说的 mouseup 应该是指 鼠标拖拉选之后 释放鼠标 抬起手指的那个 up 对吧？

我说的是在文档编辑时， 按住 键盘 Shift 然后按 ← → 方向键，也可以拖选选区。

其实我只是想说：Shift 选区这个操作在文档编辑还是很常用的，十分建议加入考虑并相对应滴做支持。

**Comment by Flrande** [comment]
艹，我第一次知道，学习了

**Comment by ShenQingchuan** [comment]
> 艹，我第一次知道，学习了

我感觉到了 （Doge

<details>
  <summary> 交流学习一下 </summary>
  https://github.com/ShenQingchuan/HeteroDoc <br>
  我也有一个类似的 富文本编辑的项目 哈哈~ 互相交流 ❤️
</details>

**Comment by Flrande** [comment]
你可以去 blocksuite 提个 issue 呀，你作为用户的影响可比我大多了😁

**Comment by ShenQingchuan** [comment]
> 你可以去 blocksuite 提个 issue 呀，你作为用户的影响可比我大多了😁

OK，这就去~

**Comment by Flrande** [comment]
> https://github.com/ShenQingchuan/HeteroDoc
> 我也有一个类似的 富文本编辑的项目 哈哈~ 互相交流 ❤️

你是不是毕设就用的这个👀

**Comment by ShenQingchuan** [comment]
> > https://github.com/ShenQingchuan/HeteroDoc
> > 我也有一个类似的 富文本编辑的项目 哈哈~ 互相交流 ❤️
> 
> 你是不是毕设就用的这个👀

这是我的重构版了，抄了 TipTap 的代码结构设计
现在只有 /playground 那里可以用，我平时就在那个页面调试

<details>
  <summary> 黑历史 </summary>

毕设是这些：
https://github.com/ShenQingchuan/bib-web-FE
https://github.com/ShenQingchuan/bib-web-BE
https://github.com/ShenQingchuan/bib-web-yjs-server


</details>
